[package]
name = "hamaddr"
version = "0.1.0"
edition = "2018"
authors = ["kz2x", "n6drc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
